# Generated by Django 5.2.4 on 2025-10-29 23:44

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatchannels_users_online_alter_chatmessage_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannels',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatchannels',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatchannels',
            name='channel_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=100, unique=True),
        ),
    ]
